from django.urls import path

from . import views


urlpatterns = [
    path("", views.home, name="home"),
    path("downloads/<uuid:share_token>/", views.public_download_file, name="public_download_file"),
    path("workspace/", views.workspace_choice, name="workspace_choice"),
    path("workspace/<str:workspace>/", views.select_workspace, name="select_workspace"),
    path("health/", views.healthcheck, name="healthcheck"),
    path("login/", views.login_page, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("supervisor/", views.supervisor_dashboard, name="supervisor_dashboard"),
    path("supervisor/users/", views.supervisor_user_management, name="supervisor_user_management"),
    path("supervisor/public-downloads/", views.public_download_list, name="public_download_list"),
    path("supervisor/public-downloads/<int:file_id>/delete/", views.public_download_delete, name="public_download_delete"),
    path(
        "supervisor/users/supervisor-access/<int:access_email_id>/delete/",
        views.supervisor_access_email_delete,
        name="supervisor_access_email_delete",
    ),
    path("supervisor/staff/", views.staff_list, name="staff_list"),
    path("supervisor/staff/add/", views.staff_create, name="staff_create"),
    path("supervisor/staff/<int:user_id>/dashboard/", views.supervisor_staff_dashboard, name="supervisor_staff_dashboard"),
    path("supervisor/staff/<int:user_id>/prospects/", views.supervisor_staff_prospect_list, name="supervisor_staff_prospect_list"),
    path("supervisor/staff/<int:user_id>/edit/", views.staff_update, name="staff_update"),
    path("supervisor/staff/<int:user_id>/delete/", views.staff_delete, name="staff_delete"),
    path("supervisor/sales-managers/", views.sales_manager_list, name="sales_manager_list"),
    path("supervisor/sales-managers/add/", views.sales_manager_create, name="sales_manager_create"),
    path("supervisor/sales-managers/<int:user_id>/edit/", views.sales_manager_update, name="sales_manager_update"),
    path("supervisor/sales-managers/<int:user_id>/delete/", views.sales_manager_delete, name="sales_manager_delete"),
    path("supervisor/finance-managers/", views.finance_manager_list, name="finance_manager_list"),
    path("supervisor/finance-managers/add/", views.finance_manager_create, name="finance_manager_create"),
    path("supervisor/finance-managers/<int:user_id>/edit/", views.finance_manager_update, name="finance_manager_update"),
    path("supervisor/finance-managers/<int:user_id>/delete/", views.finance_manager_delete, name="finance_manager_delete"),
    path("supervisor/business-managers/add/", views.business_manager_create, name="business_manager_create"),
    path("supervisor/business-managers/<int:user_id>/edit/", views.business_manager_update, name="business_manager_update"),
    path("supervisor/business-managers/<int:user_id>/delete/", views.business_manager_delete, name="business_manager_delete"),
    path("supervisor/marketing-managers/add/", views.marketing_manager_create, name="marketing_manager_create"),
    path("supervisor/marketing-managers/<int:user_id>/edit/", views.marketing_manager_update, name="marketing_manager_update"),
    path("supervisor/marketing-managers/<int:user_id>/delete/", views.marketing_manager_delete, name="marketing_manager_delete"),
    path("supervisor/prospects/", views.supervisor_prospect_list, name="supervisor_prospect_list"),
    path("supervisor/prospects/review/", views.supervisor_prospect_review, name="supervisor_prospect_review"),
    path("supervisor/prospects/invalid/", views.supervisor_invalid_prospect_list, name="supervisor_invalid_prospect_list"),
    path("supervisor/prospects/supervisor-action/", views.supervisor_action_prospect_list, name="supervisor_action_prospect_list"),
    path("supervisor/prospects/add/", views.supervisor_prospect_create, name="supervisor_prospect_create"),
    path("supervisor/prospects/<int:prospect_id>/move/", views.supervisor_move_prospect, name="supervisor_move_prospect"),
    path("supervisor/prospects/<int:prospect_id>/delete/", views.supervisor_prospect_delete, name="supervisor_prospect_delete"),
    path("supervisor/prospects/<int:prospect_id>/manage/", views.supervisor_action_prospect_manage, name="supervisor_action_prospect_manage"),
    path("supervisor/prospects/<int:prospect_id>/review/", views.review_prospect, name="review_prospect"),
    path("supervisor/imports/", views.import_batch_create, name="import_batch_create"),
    path("supervisor/meetings/", views.supervisor_meeting_list, name="supervisor_meeting_list"),
    path("supervisor/reminders/", views.supervisor_reminder_dashboard, name="supervisor_reminder_dashboard"),
    path("supervisor/meetings/<int:meeting_id>/status/", views.update_meeting_status, name="update_meeting_status"),
    path("supervisor/meetings/<int:meeting_id>/delete/", views.supervisor_meeting_delete, name="supervisor_meeting_delete"),
    path("supervisor/settings/", views.system_settings_view, name="system_settings"),
    path("supervisor/reports/", views.supervisor_reports, name="supervisor_reports"),
    path("supervisor/daily-targets/", views.supervisor_daily_targets, name="supervisor_daily_targets"),
    path("supervisor/direct-marketing/", views.direct_marketing_create, name="direct_marketing_create"),
    path("supervisor/direct-marketing/list/", views.direct_marketing_list, name="direct_marketing_list"),
    path("cashflow/", views.cashflow_dashboard, name="cashflow_dashboard"),
    path("cashflow/uploads/", views.cashflow_uploads, name="cashflow_uploads"),
    path("cashflow/action-centre/", views.cashflow_action_centre, name="cashflow_action_centre"),
    path("cashflow/outflows/", views.cashflow_outflow_list, name="cashflow_outflow_list"),
    path("cashflow/outflows/<int:item_id>/", views.cashflow_outflow_update, name="cashflow_outflow_update"),
    path(
        "cashflow/collections/installments/<int:installment_id>/revise/",
        views.cashflow_overdue_installment_update,
        name="cashflow_overdue_installment_update",
    ),
    path("cashflow/projected-collections/", views.cashflow_projected_collection_list, name="cashflow_projected_collection_list"),
    path(
        "cashflow/projected-collections/add/",
        views.cashflow_projected_collection_create,
        name="cashflow_projected_collection_create",
    ),
    path(
        "cashflow/projected-collections/<int:collection_id>/",
        views.cashflow_projected_collection_update,
        name="cashflow_projected_collection_update",
    ),
    path("cashflow/work-orders/", views.cashflow_work_order_list, name="cashflow_work_order_list"),
    path("cashflow/work-orders/add/", views.cashflow_work_order_create, name="cashflow_work_order_create"),
    path("cashflow/projection/", views.cashflow_projection_view, name="cashflow_projection"),
    path(
        "cashflow/projection/week/<int:week_index>/",
        views.cashflow_projection_week_detail,
        name="cashflow_projection_week_detail",
    ),
    path("marketing/", views.marketing_dashboard, name="marketing_dashboard"),
    path("marketing/playbooks/", views.marketing_playbook_list, name="marketing_playbook_list"),
    path("marketing/playbooks/add/", views.marketing_playbook_create, name="marketing_playbook_create"),
    path("marketing/playbooks/<int:playbook_id>/", views.marketing_playbook_update, name="marketing_playbook_update"),
    path("marketing/pharma-managers/", views.pharma_manager_list, name="pharma_manager_list"),
    path("marketing/pharma-managers/add/", views.pharma_manager_create, name="pharma_manager_create"),
    path("marketing/pharma-managers/<int:pharma_manager_id>/", views.pharma_manager_update, name="pharma_manager_update"),
    path("marketing/pharma-managers/<int:pharma_manager_id>/delete/", views.pharma_manager_delete, name="pharma_manager_delete"),
    path("marketing/email-campaigns/send/", views.marketing_email_campaign_create, name="marketing_email_campaign_create"),
    path("marketing/linkedin-activity/add/", views.marketing_linkedin_activity_create, name="marketing_linkedin_activity_create"),
    path("marketing/pharma-manager-upload/", views.pharma_manager_upload_create, name="pharma_manager_upload"),
    path("sales/", views.sales_pipeline_dashboard, name="sales_pipeline_dashboard"),
    path("sales/add/", views.sales_conversation_create, name="sales_conversation_create"),
    path("sales/<int:conversation_id>/", views.sales_conversation_update, name="sales_conversation_update"),
    path("sales/<int:conversation_id>/delete/", views.sales_conversation_delete, name="sales_conversation_delete"),
    path("contracts/", views.contracts_dashboard, name="contracts_dashboard"),
    path("contracts/add/", views.contract_collection_create, name="contract_collection_create"),
    path("contracts/<int:contract_id>/", views.contract_collection_update, name="contract_collection_update"),
    path("contracts/pending-collections/", views.pending_collections_view, name="pending_collections"),
    path("contracts/send-invoice-due-notifications/", views.send_invoice_due_notifications_now, name="send_invoice_due_notifications_now"),
    path("staff/dashboard/", views.staff_dashboard, name="staff_dashboard"),
    path("staff/prospects/", views.staff_prospect_list, name="staff_prospect_list"),
    path("staff/prospects/add/", views.staff_prospect_create, name="staff_prospect_create"),
    path("staff/prospects/<int:prospect_id>/update-call/", views.update_call_outcome, name="update_call_outcome"),
    path("staff/meetings/", views.staff_meeting_list, name="staff_meeting_list"),
    path("staff/meetings/<int:meeting_id>/reminders/", views.log_meeting_reminder, name="log_meeting_reminder"),
]
