from django.urls import path

from . import views


urlpatterns = [
    path("", views.home, name="home"),
    path("downloads/<uuid:share_token>/", views.public_download_file, name="public_download_file"),
    path("workspace/", views.workspace_choice, name="workspace_choice"),
    path("workspace/<str:workspace>/", views.select_workspace, name="select_workspace"),
    path("health/", views.healthcheck, name="healthcheck"),
    path("login/", views.login_page, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("supervisor/", views.supervisor_dashboard, name="supervisor_dashboard"),
    path("supervisor/users/", views.supervisor_user_management, name="supervisor_user_management"),
    path("supervisor/public-downloads/", views.public_download_list, name="public_download_list"),
    path("supervisor/public-downloads/<int:file_id>/delete/", views.public_download_delete, name="public_download_delete"),
    path(
        "supervisor/users/supervisor-access/<int:access_email_id>/delete/",
        views.supervisor_access_email_delete,
        name="supervisor_access_email_delete",
    ),
    path("supervisor/staff/", views.staff_list, name="staff_list"),
    path("supervisor/staff/add/", views.staff_create, name="staff_create"),
    path("supervisor/staff/<int:user_id>/dashboard/", views.supervisor_staff_dashboard, name="supervisor_staff_dashboard"),
    path("supervisor/staff/<int:user_id>/prospects/", views.supervisor_staff_prospect_list, name="supervisor_staff_prospect_list"),
    path("supervisor/staff/<int:user_id>/edit/", views.staff_update, name="staff_update"),
    path("supervisor/staff/<int:user_id>/delete/", views.staff_delete, name="staff_delete"),
    path("supervisor/sales-managers/", views.sales_manager_list, name="sales_manager_list"),
    path("supervisor/sales-managers/add/", views.sales_manager_create, name="sales_manager_create"),
    path("supervisor/sales-managers/<int:user_id>/edit/", views.sales_manager_update, name="sales_manager_update"),
    path("supervisor/sales-managers/<int:user_id>/delete/", views.sales_manager_delete, name="sales_manager_delete"),
    path("supervisor/finance-managers/", views.finance_manager_list, name="finance_manager_list"),
    path("supervisor/finance-managers/add/", views.finance_manager_create, name="finance_manager_create"),
    path("supervisor/finance-managers/<int:user_id>/edit/", views.finance_manager_update, name="finance_manager_update"),
    path("supervisor/finance-managers/<int:user_id>/delete/", views.finance_manager_delete, name="finance_manager_delete"),
    path("supervisor/prospects/", views.supervisor_prospect_list, name="supervisor_prospect_list"),
    path("supervisor/prospects/review/", views.supervisor_prospect_review, name="supervisor_prospect_review"),
    path("supervisor/prospects/invalid/", views.supervisor_invalid_prospect_list, name="supervisor_invalid_prospect_list"),
    path("supervisor/prospects/supervisor-action/", views.supervisor_action_prospect_list, name="supervisor_action_prospect_list"),
    path("supervisor/prospects/add/", views.supervisor_prospect_create, name="supervisor_prospect_create"),
    path("supervisor/prospects/<int:prospect_id>/move/", views.supervisor_move_prospect, name="supervisor_move_prospect"),
    path("supervisor/prospects/<int:prospect_id>/delete/", views.supervisor_prospect_delete, name="supervisor_prospect_delete"),
    path("supervisor/prospects/<int:prospect_id>/manage/", views.supervisor_action_prospect_manage, name="supervisor_action_prospect_manage"),
    path("supervisor/prospects/<int:prospect_id>/review/", views.review_prospect, name="review_prospect"),
    path("supervisor/imports/", views.import_batch_create, name="import_batch_create"),
    path("supervisor/meetings/", views.supervisor_meeting_list, name="supervisor_meeting_list"),
    path("supervisor/reminders/", views.supervisor_reminder_dashboard, name="supervisor_reminder_dashboard"),
    path("supervisor/meetings/<int:meeting_id>/status/", views.update_meeting_status, name="update_meeting_status"),
    path("supervisor/meetings/<int:meeting_id>/delete/", views.supervisor_meeting_delete, name="supervisor_meeting_delete"),
    path("supervisor/settings/", views.system_settings_view, name="system_settings"),
    path("supervisor/reports/", views.supervisor_reports, name="supervisor_reports"),
    path("supervisor/daily-targets/", views.supervisor_daily_targets, name="supervisor_daily_targets"),
    path("sales/", views.sales_pipeline_dashboard, name="sales_pipeline_dashboard"),
    path("sales/add/", views.sales_conversation_create, name="sales_conversation_create"),
    path("sales/<int:conversation_id>/", views.sales_conversation_update, name="sales_conversation_update"),
    path("contracts/", views.contracts_dashboard, name="contracts_dashboard"),
    path("contracts/add/", views.contract_collection_create, name="contract_collection_create"),
    path("contracts/<int:contract_id>/", views.contract_collection_update, name="contract_collection_update"),
    path("contracts/pending-collections/", views.pending_collections_view, name="pending_collections"),
    path("contracts/send-invoice-due-notifications/", views.send_invoice_due_notifications_now, name="send_invoice_due_notifications_now"),
    path("staff/dashboard/", views.staff_dashboard, name="staff_dashboard"),
    path("staff/prospects/", views.staff_prospect_list, name="staff_prospect_list"),
    path("staff/prospects/add/", views.staff_prospect_create, name="staff_prospect_create"),
    path("staff/prospects/<int:prospect_id>/update-call/", views.update_call_outcome, name="update_call_outcome"),
    path("staff/meetings/", views.staff_meeting_list, name="staff_meeting_list"),
    path("staff/meetings/<int:meeting_id>/reminders/", views.log_meeting_reminder, name="log_meeting_reminder"),
]
