# Generated by Django 5.2.12 on 2026-03-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('leadgen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['started_at', 'staff'], name='leadgen_cal_started_f8fdd6_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['started_at', 'crm_status'], name='leadgen_cal_started_563438_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['scheduled_for', 'status'], name='leadgen_mee_schedul_f92052_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['created_at', 'status'], name='leadgen_mee_created_0d7ee5_idx'),
        ),
        migrations.AddIndex(
            model_name='prospectstatusupdate',
            index=models.Index(fields=['created_at', 'outcome'], name='leadgen_pro_created_1a5275_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'supervisor')), fields=('role',), name='unique_supervisor_user'),
        ),
    ]
