# Generated by Django 5.2.12 on 2026-04-04 07:26

import django.db.models.deletion
import leadgen.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgen', '0002_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('staff', 'Lead Gen Staff'), ('sales_manager', 'Sales Manager')], default='staff', max_length=20),
        ),
        migrations.CreateModel(
            name='SalesConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_conversation_id', models.CharField(default=leadgen.models.generate_sales_conversation_id, editable=False, max_length=32, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('conversation_status', models.CharField(choices=[('engaged', 'Engaged'), ('not_engaged', 'Not engaged'), ('to_be_revived', 'To be revived'), ('deeply_engaged', 'Deeply engaged'), ('in_negotiations', 'In negotiations'), ('in_contracting', 'In contracting')], default='engaged', max_length=32)),
                ('proposal_status', models.CharField(choices=[('solution_needed', 'Solution needed'), ('solution_given', 'Solution given'), ('need_updated_solution', 'Need updated solution'), ('proposal_needed', 'Proposal needed'), ('proposal_given', 'Proposal given')], default='solution_needed', max_length=32)),
                ('contract_signed', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_sales_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_conversations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sales_conversations', to=settings.AUTH_USER_MODEL)),
                ('source_meeting', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_conversation', to='leadgen.meeting')),
            ],
            options={
                'ordering': ['contract_signed', '-updated_at', 'company_name'],
            },
        ),
        migrations.CreateModel(
            name='SalesConversationBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sales_conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='leadgen.salesconversation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalesConversationContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('sales_conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='leadgen.salesconversation')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='SalesConversationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('solution', 'Solution'), ('proposal', 'Proposal')], max_length=20)),
                ('file', models.FileField(upload_to='sales_pipeline/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sales_conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='leadgen.salesconversation')),
            ],
            options={
                'ordering': ['category', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='salesconversation',
            index=models.Index(fields=['contract_signed', 'conversation_status'], name='leadgen_sal_contrac_16e01f_idx'),
        ),
        migrations.AddIndex(
            model_name='salesconversation',
            index=models.Index(fields=['assigned_sales_manager', 'contract_signed'], name='leadgen_sal_assigne_c4f1b7_idx'),
        ),
        migrations.AddIndex(
            model_name='salesconversation',
            index=models.Index(fields=['proposal_status', 'contract_signed'], name='leadgen_sal_proposa_61b208_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesconversationcontact',
            constraint=models.UniqueConstraint(fields=('sales_conversation', 'position'), name='unique_sales_contact_position'),
        ),
    ]
