# Generated by Codex on 2026-04-04

from django.contrib.auth.hashers import make_password
from django.db import migrations


def seed_initial_sales_manager(apps, schema_editor):
    User = apps.get_model("leadgen", "User")
    email = "amit@inditech.co.in"
    user, _ = User.objects.get_or_create(
        email=email,
        defaults={
            "username": email,
            "name": "Amit",
            "role": "sales_manager",
            "is_active": True,
        },
    )
    user.username = email
    user.email = email
    user.name = user.name or "Amit"
    user.role = "sales_manager"
    user.calling_number = None
    user.must_change_password = False
    user.password = make_password(None)
    user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("leadgen", "0003_alter_user_role_salesconversation_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_initial_sales_manager, migrations.RunPython.noop),
    ]
