# Generated by Django 5.2.12 on 2026-04-04 11:23

import django.db.models.deletion
import leadgen.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgen', '0004_seed_initial_sales_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('staff', 'Lead Gen Staff'), ('sales_manager', 'Sales Manager'), ('finance_manager', 'Finance Manager')], default='staff', max_length=20),
        ),
        migrations.CreateModel(
            name='ContractCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_collection_id', models.CharField(default=leadgen.models.generate_contract_collection_id, editable=False, max_length=32, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('contract_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_contract_collections', to=settings.AUTH_USER_MODEL)),
                ('sales_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_collections', to=settings.AUTH_USER_MODEL)),
                ('source_sales_conversation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_collection', to='leadgen.salesconversation')),
            ],
            options={
                'ordering': ['-updated_at', 'company_name'],
            },
        ),
        migrations.CreateModel(
            name='ContractCollectionContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('contract_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='leadgen.contractcollection')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ContractCollectionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contracts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='leadgen.contractcollection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractCollectionInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('installment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('expected_collection_date', models.DateField(blank=True, null=True)),
                ('revised_collection_date', models.DateField(blank=True, null=True)),
                ('collected_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('collection_date', models.DateField(blank=True, null=True)),
                ('invoice_notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('contract_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='leadgen.contractcollection')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='contractcollection',
            index=models.Index(fields=['sales_manager', 'updated_at'], name='leadgen_con_sales_m_0f9ab7_idx'),
        ),
        migrations.AddConstraint(
            model_name='contractcollectioncontact',
            constraint=models.UniqueConstraint(fields=('contract_collection', 'position'), name='unique_contract_contact_position'),
        ),
        migrations.AddIndex(
            model_name='contractcollectioninstallment',
            index=models.Index(fields=['invoice_date', 'collection_date'], name='leadgen_con_invoice_59901c_idx'),
        ),
        migrations.AddIndex(
            model_name='contractcollectioninstallment',
            index=models.Index(fields=['expected_collection_date', 'revised_collection_date'], name='leadgen_con_expecte_8b3fb3_idx'),
        ),
        migrations.AddConstraint(
            model_name='contractcollectioninstallment',
            constraint=models.UniqueConstraint(fields=('contract_collection', 'position'), name='unique_contract_installment_position'),
        ),
    ]
