# Generated by Django 5.2.12 on 2026-04-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgen', '0005_alter_user_role_contractcollection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='no_answer_reset_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prospect',
            name='system_action_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='workflow_status',
            field=models.CharField(choices=[('pending_review', 'Pending review'), ('ready_to_call', 'Ready to call'), ('follow_up_to_schedule', 'Follow up to schedule'), ('does_not_agree', 'Does not agree'), ('scheduled', 'Scheduled'), ('meeting_happened', 'Meeting happened'), ('supervisor_action_required', 'Supervisor action required'), ('invalid_number', 'Invalid number')], default='pending_review', max_length=40),
        ),
    ]
