# Generated by Django 5.2.12 on 2026-04-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgen', '0006_prospect_no_answer_reset_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_platform',
            field=models.CharField(blank=True, choices=[('teams', 'Teams meeting'), ('zoom', 'Zoom meeting')], default='', max_length=20),
        ),
    ]
