# Generated by Django 5.2.12 on 2026-04-07 08:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgen', '0007_meeting_meeting_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('whatsapp_initial', 'First WhatsApp reminder'), ('email_day_before', '24-hour reminder email'), ('email_same_day', 'Same-day reminder email'), ('whatsapp_final', 'Final WhatsApp reminder')], max_length=32)),
                ('recipient_number', models.CharField(blank=True, max_length=20)),
                ('screenshot', models.FileField(blank=True, upload_to='meeting-reminders/')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='leadgen.meeting')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sent_at', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('meeting', 'reminder_type'), name='unique_meeting_reminder_type')],
            },
        ),
    ]
