# Generated by Django 5.2.12 on 2026-04-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgen', '0008_meetingreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractcollectioninstallment',
            name='contract_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contractcollectioninstallment',
            name='invoiced_service_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contractcollectioninstallment',
            name='legal_due_reason',
            field=models.TextField(blank=True),
        ),
    ]
