# Generated by Django 5.2.12 on 2026-04-23 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgen', '0015_publicdownloadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name='DirectMarketingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('therapy_area', models.CharField(max_length=255)),
                ('sent_on', models.DateField()),
                ('prospect_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direct_marketing_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_on', '-created_at'],
                'indexes': [models.Index(fields=['sent_on', 'therapy_area'], name='leadgen_dir_sent_on_8e3148_idx')],
            },
        ),
    ]
