# Generated by Django 5.2.12 on 2026-04-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgen', '0016_alter_user_email_directmarketingactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('happened', 'Meeting happened'), ('did_not_happen', 'Did not happen'), ('no_show', 'Meeting did not happen - no show'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='meetingreminder',
            name='reminder_type',
            field=models.CharField(choices=[('whatsapp_initial', 'First WhatsApp reminder'), ('whatsapp_pre_meeting', 'Pre-meeting WhatsApp reminder'), ('email_day_before', '24-hour reminder email'), ('email_same_day', 'Same-day reminder email'), ('whatsapp_final', 'Final WhatsApp reminder'), ('whatsapp_no_show', '48-hour no-show WhatsApp'), ('whatsapp_28_day', '28-day follow-up WhatsApp')], max_length=32),
        ),
    ]
