# Generated by Django 5.2.12 on 2026-04-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgen', '0017_alter_meeting_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesconversation',
            name='next_action_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='salesconversation',
            index=models.Index(fields=['next_action_date', 'contract_signed'], name='leadgen_sal_next_ac_160544_idx'),
        ),
    ]
