# Generated by Django 5.2.12 on 2026-04-26 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgen', '0018_salesconversation_next_action_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('staff', 'Lead Gen Staff'), ('sales_manager', 'Sales Manager'), ('finance_manager', 'Finance Manager'), ('business_manager', 'Business Manager')], default='staff', max_length=20),
        ),
        migrations.CreateModel(
            name='CashflowSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_date', models.DateField()),
                ('payables_file', models.FileField(upload_to='cashflow-imports/')),
                ('provisions_file', models.FileField(upload_to='cashflow-imports/')),
                ('receivables_file', models.FileField(upload_to='cashflow-imports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashflow_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-as_of_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashflowImportedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('payable', 'Payable'), ('provision', 'Provision'), ('receivable', 'Receivable')], max_length=20)),
                ('source_key', models.CharField(max_length=255)),
                ('party_name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('reference_number', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('primary_classification', models.CharField(blank=True, max_length=255)),
                ('secondary_classification', models.CharField(blank=True, max_length=255)),
                ('cost_type', models.CharField(blank=True, choices=[('one_time', 'One-time cost'), ('recurring_monthly', 'Repetitive monthly cost')], max_length=32)),
                ('recurring_payable_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('raw_row', models.JSONField(blank=True, default=dict)),
                ('is_current', models.BooleanField(default=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='leadgen.cashflowsnapshot')),
            ],
            options={
                'ordering': ['category', 'party_name', 'reference_number', 'description'],
            },
        ),
        migrations.CreateModel(
            name='CashflowWorkOrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('party_name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashflow_work_order_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashflowWorkOrderInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_date', models.DateField()),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='leadgen.cashflowworkorderrequest')),
            ],
            options={
                'ordering': ['position', 'payment_date'],
            },
        ),
        migrations.CreateModel(
            name='CashflowPaymentPlanEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cashflow_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='leadgen.cashflowimporteditem')),
            ],
            options={
                'ordering': ['payment_date', 'pk'],
                'indexes': [models.Index(fields=['payment_date'], name='leadgen_cas_payment_ca9be4_idx')],
            },
        ),
        migrations.CreateModel(
            name='CashflowProjectedCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expected_collection_date', models.DateField()),
                ('revised_collection_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashflow_projected_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['expected_collection_date', 'company_name'],
                'indexes': [models.Index(fields=['expected_collection_date', 'revised_collection_date'], name='leadgen_cas_expecte_377e14_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='cashflowsnapshot',
            index=models.Index(fields=['as_of_date', 'created_at'], name='leadgen_cas_as_of_d_a42c36_idx'),
        ),
        migrations.AddIndex(
            model_name='cashflowimporteditem',
            index=models.Index(fields=['category', 'is_current'], name='leadgen_cas_categor_aacc5d_idx'),
        ),
        migrations.AddIndex(
            model_name='cashflowimporteditem',
            index=models.Index(fields=['due_date', 'category'], name='leadgen_cas_due_dat_07a985_idx'),
        ),
        migrations.AddIndex(
            model_name='cashflowimporteditem',
            index=models.Index(fields=['primary_classification', 'secondary_classification'], name='leadgen_cas_primary_e3d1df_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashflowimporteditem',
            constraint=models.UniqueConstraint(fields=('category', 'source_key'), name='unique_cashflow_imported_item_source'),
        ),
        migrations.AddConstraint(
            model_name='cashflowworkorderinstallment',
            constraint=models.UniqueConstraint(fields=('work_order', 'position'), name='unique_cashflow_work_order_installment_position'),
        ),
    ]
