# Generated by Django 5.2.12 on 2026-04-27 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadgen', '0019_alter_user_role_cashflowsnapshot_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_supervisor_user',
        ),
    ]
