# Generated by Django 5.2.12 on 2026-04-30 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgen', '0020_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('staff', 'Lead Gen Staff'), ('sales_manager', 'Sales Manager'), ('finance_manager', 'Finance Manager'), ('business_manager', 'Business Manager'), ('marketing_manager', 'Marketing Manager')], default='staff', max_length=20),
        ),
        migrations.CreateModel(
            name='MarketingPlaybook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('therapy_area', models.CharField(max_length=255)),
                ('molecule_or_formulation', models.CharField(max_length=255)),
                ('website_download_url', models.URLField()),
                ('pdf_file', models.FileField(upload_to='marketing-playbooks/')),
                ('notion_page_url', models.URLField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('linkedin_invitation_message', models.TextField()),
                ('direct_email_subject', models.CharField(max_length=255)),
                ('direct_email_body', models.TextField()),
                ('linkedin_connected_message', models.TextField()),
                ('targeted_email_subject', models.CharField(max_length=255)),
                ('targeted_email_body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketing_playbooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MarketingLinkedInActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('invitations', 'Sales Navigator invitations'), ('messages', 'LinkedIn messages')], max_length=32)),
                ('activity_start_date', models.DateField()),
                ('activity_end_date', models.DateField()),
                ('count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketing_linkedin_activities', to=settings.AUTH_USER_MODEL)),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linkedin_activities', to='leadgen.marketingplaybook')),
            ],
            options={
                'ordering': ['-activity_end_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingEmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_type', models.CharField(choices=[('full_database', 'Entire pharma manager database'), ('molecule_targeted', 'Molecule/formulation targeted database')], max_length=32)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketing_email_campaigns', to=settings.AUTH_USER_MODEL)),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_campaigns', to='leadgen.marketingplaybook')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='PharmaManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('therapy_area_1', models.CharField(blank=True, max_length=255)),
                ('therapy_area_2', models.CharField(blank=True, max_length=255)),
                ('therapy_area_3', models.CharField(blank=True, max_length=255)),
                ('therapy_area_4', models.CharField(blank=True, max_length=255)),
                ('therapy_area_5', models.CharField(blank=True, max_length=255)),
                ('molecule_1', models.CharField(blank=True, max_length=255)),
                ('molecule_2', models.CharField(blank=True, max_length=255)),
                ('molecule_3', models.CharField(blank=True, max_length=255)),
                ('molecule_4', models.CharField(blank=True, max_length=255)),
                ('molecule_5', models.CharField(blank=True, max_length=255)),
                ('molecule_6', models.CharField(blank=True, max_length=255)),
                ('molecule_7', models.CharField(blank=True, max_length=255)),
                ('molecule_8', models.CharField(blank=True, max_length=255)),
                ('molecule_9', models.CharField(blank=True, max_length=255)),
                ('molecule_10', models.CharField(blank=True, max_length=255)),
                ('linkedin_url', models.URLField(blank=True)),
                ('unsubscribed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_pharma_managers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'company_name'],
            },
        ),
        migrations.CreateModel(
            name='PharmaManagerUploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('molecule_or_formulation', models.CharField(max_length=255)),
                ('therapy_area', models.CharField(blank=True, max_length=255)),
                ('uploaded_file', models.FileField(upload_to='marketing-pharma-manager-imports/')),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pharma_manager_upload_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='marketingplaybook',
            index=models.Index(fields=['start_date', 'end_date'], name='leadgen_mar_start_d_a9937b_idx'),
        ),
        migrations.AddIndex(
            model_name='marketingplaybook',
            index=models.Index(fields=['therapy_area', 'molecule_or_formulation'], name='leadgen_mar_therapy_c5eca1_idx'),
        ),
        migrations.AddIndex(
            model_name='marketingemailcampaign',
            index=models.Index(fields=['campaign_type', 'sent_at'], name='leadgen_mar_campaig_306660_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmamanager',
            index=models.Index(fields=['name', 'company_name'], name='leadgen_pha_name_b6ac3f_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmamanager',
            index=models.Index(fields=['unsubscribed', 'email'], name='leadgen_pha_unsubsc_fdb977_idx'),
        ),
    ]
