# Generated by Django 5.2.12 on 2026-05-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgen', '0021_alter_user_role_marketingplaybook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowsnapshot',
            name='proforma_receivables_file',
            field=models.FileField(blank=True, null=True, upload_to='cashflow-imports/'),
        ),
    ]
