# Generated by Django 5.2.12 on 2026-05-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgen', '0022_cashflowsnapshot_proforma_receivables_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingemailcampaign',
            name='attachment_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='marketingemailcampaign',
            name='target_molecules',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='marketingemailcampaign',
            name='target_therapy_areas',
            field=models.TextField(blank=True),
        ),
    ]
