# Generated by Django 5.2.12 on 2026-05-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgen', '0023_marketingemailcampaign_attachment_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='cashflow_opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
