# Generated by Django 5.2.12 on 2026-05-15 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgen', '0024_systemsetting_cashflow_opening_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashflowManualEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('debt', 'Debt'), ('tds', 'TDS'), ('gst', 'GST')], max_length=16)),
                ('direction', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transaction_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashflow_manual_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date', '-updated_at', '-pk'],
                'indexes': [models.Index(fields=['transaction_date', 'direction'], name='leadgen_cas_transac_295546_idx'), models.Index(fields=['category', 'transaction_date'], name='leadgen_cas_categor_5c6a6b_idx')],
            },
        ),
    ]
