# Generated by Django 5.2.12 on 2026-05-18 06:34

from django.db import migrations, models


TEST_ACCOUNT_EMAILS = [
    "test.1.tanisha.bhadula@inditech.co.in",
    "test.2.tanisha.bhadula@inditech.co.in",
    "test.3.tanisha.bhadula@inditech.co.in",
    "test.4.tanisha.bhadula@inditech.co.in",
    "test.5.tanisha.bhadula@inditech.co.in",
    "test.6.tanisha.bhadula@inditech.co.in",
    "test.7.tanisha.bhadula@inditech.co.in",
    "test.8.tanisha.bhadula@inditech.co.in",
    "test.9.tanisha.bhadula@inditech.co.in",
    "test.10.tanisha.bhadula@inditech.co.in",
]


def mark_test_accounts(apps, schema_editor):
    PharmaManager = apps.get_model("leadgen", "PharmaManager")
    for index, email in enumerate(TEST_ACCOUNT_EMAILS, start=1):
        pharma_manager, _ = PharmaManager.objects.get_or_create(
            email=email,
            defaults={
                "name": f"Test Account {index}",
                "company_name": "Inditech Test Account",
                "is_test_account": True,
            },
        )
        if not pharma_manager.is_test_account:
            pharma_manager.is_test_account = True
            pharma_manager.save(update_fields=["is_test_account"])


def unmark_test_accounts(apps, schema_editor):
    PharmaManager = apps.get_model("leadgen", "PharmaManager")
    PharmaManager.objects.filter(email__in=TEST_ACCOUNT_EMAILS).update(is_test_account=False)


class Migration(migrations.Migration):

    dependencies = [
        ('leadgen', '0025_cashflowmanualentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingemailcampaign',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketingemailcampaign',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='marketingemailcampaign',
            name='expected_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marketingemailcampaign',
            name='is_test_campaign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketingemailcampaign',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketingemailcampaign',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='pharmamanager',
            name='is_test_account',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_test_accounts, unmark_test_accounts),
        migrations.AddIndex(
            model_name='pharmamanager',
            index=models.Index(fields=['is_test_account', 'unsubscribed'], name='leadgen_pha_is_test_2537e1_idx'),
        ),
    ]
