# Generated by Django 5.2.12 on 2026-06-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leadgen", "0029_salesconversation_inbound_inquiries_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketingplaybook",
            name="pdf_file",
            field=models.FileField(blank=True, upload_to="marketing-playbooks/"),
        ),
    ]
