# Generated by Django 5.2.12 on 2026-06-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leadgen", "0030_alter_marketingplaybook_pdf_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prospect",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
