# Generated by Django 5.2.12 on 2026-06-30 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_default_providers(apps, schema_editor):
    LeadgenServiceProvider = apps.get_model("leadgen", "LeadgenServiceProvider")
    for display_order, name in enumerate(["Ninad (SDI)", "Nilesh (S2P)"], start=1):
        LeadgenServiceProvider.objects.get_or_create(
            name=name,
            defaults={"display_order": display_order, "is_active": True},
        )


def unseed_default_providers(apps, schema_editor):
    LeadgenServiceProvider = apps.get_model("leadgen", "LeadgenServiceProvider")
    LeadgenServiceProvider.objects.filter(name__in=["Ninad (SDI)", "Nilesh (S2P)"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("leadgen", "0031_alter_prospect_phone_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadgenServiceProvider",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="LeadgenProviderWeeklyTarget",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("week_start_date", models.DateField()),
                ("daily_reachout_target", models.PositiveIntegerField(default=0)),
                ("weekly_reachout_target", models.PositiveIntegerField(default=0)),
                ("weekly_connection_acceptance_target", models.PositiveIntegerField(default=0)),
                ("weekly_meeting_target", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_provider_weekly_targets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_targets",
                        to="leadgen.leadgenserviceprovider",
                    ),
                ),
            ],
            options={
                "ordering": ["-week_start_date", "provider__display_order", "provider__name"],
            },
        ),
        migrations.CreateModel(
            name="LeadgenProviderDailyActivity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("activity_date", models.DateField()),
                ("prospects_reached_out", models.PositiveIntegerField(default=0)),
                ("connections_accepted", models.PositiveIntegerField(default=0)),
                ("meetings_scheduled", models.PositiveIntegerField(default=0)),
                ("meetings_done", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_activities",
                        to="leadgen.leadgenserviceprovider",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recorded_provider_daily_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-activity_date", "provider__display_order", "provider__name"],
            },
        ),
        migrations.CreateModel(
            name="LeadgenProviderActivityBaseline",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("baseline_date", models.DateField()),
                ("cumulative_reachouts", models.PositiveIntegerField(default=0)),
                ("cumulative_connections_accepted", models.PositiveIntegerField(default=0)),
                ("cumulative_meetings_scheduled", models.PositiveIntegerField(default=0)),
                ("cumulative_meetings_done", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_baselines",
                        to="leadgen.leadgenserviceprovider",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recorded_provider_activity_baselines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-baseline_date", "provider__display_order", "provider__name"],
            },
        ),
        migrations.AddIndex(
            model_name="leadgenproviderweeklytarget",
            index=models.Index(fields=["week_start_date", "provider"], name="leadgen_lea_week_st_37e64e_idx"),
        ),
        migrations.AddIndex(
            model_name="leadgenproviderdailyactivity",
            index=models.Index(fields=["activity_date", "provider"], name="leadgen_lea_activit_05eb84_idx"),
        ),
        migrations.AddIndex(
            model_name="leadgenprovideractivitybaseline",
            index=models.Index(fields=["baseline_date", "provider"], name="leadgen_lea_baselin_e9363a_idx"),
        ),
        migrations.AddConstraint(
            model_name="leadgenproviderweeklytarget",
            constraint=models.UniqueConstraint(fields=("provider", "week_start_date"), name="unique_provider_weekly_target"),
        ),
        migrations.AddConstraint(
            model_name="leadgenproviderdailyactivity",
            constraint=models.UniqueConstraint(fields=("provider", "activity_date"), name="unique_provider_daily_activity"),
        ),
        migrations.AddConstraint(
            model_name="leadgenprovideractivitybaseline",
            constraint=models.UniqueConstraint(fields=("provider", "baseline_date"), name="unique_provider_activity_baseline"),
        ),
        migrations.RunPython(seed_default_providers, unseed_default_providers),
    ]
